### ISSUE TITLE
Loop over vectorized code

### ISSUE THREAD

**Issue by vandalt** [kammerje/jwst-kpi#18]
I think there is a loop over vectorized code in the trim step:

https://github.com/kammerje/jwst-kpi/blob/41abac728f870538973dd4293f130141ccfc2206/jwst_kpi/calwebb_kpi3.py#L324-L339

The loop variable is not used and the code does the operation on all frames with `:` I believe.

**Comment by kammerje** [comment]
Yes, that seems like a bug!
